Version 1.1.0
Version 1.1.0
o Exports new APPDIR_ROOT variable.
o Now checks for target binary after POST_PUBLISH (instead of before) in case this command actually creates it.
o Does not create/overwrite AppRun if POST_PUBLISH creates it.

diff --git a/publish-appimage b/publish-appimage
--- a/publish-appimage
+++ b/publish-appimage
@@ -10,7 +10,7 @@
 # CONSTANTS
 ###############################
 
-declare -r _SCRIPT_VERSION="1.0.0"
+declare -r _SCRIPT_VERSION="1.1.0"
 declare -r _SCRIPT_TITLE="Publish-AppImage for .NET"
 declare -r _SCRIPT_IMPL_MIN=1
 declare -r _SCRIPT_IMPL_MAX=1
@@ -411,18 +411,18 @@ else
 fi
 
 # APPDIR LOCATIONS
-_appdir_root="${PKG_OUTPUT_DIR}/AppDir"
+export APPDIR_ROOT="${PKG_OUTPUT_DIR}/AppDir"
 
 if [ "${_kind_arg_value}" == "${_APPIMAGE_KIND}" ]; then
     # AppImage
-    export APPDIR_USR="${_appdir_root}/usr"
-    export APPDIR_BIN="${_appdir_root}/usr/bin"
+    export APPDIR_USR="${APPDIR_ROOT}/usr"
+    export APPDIR_BIN="${APPDIR_ROOT}/usr/bin"
 
     _apprun_target="usr/bin/${APP_MAIN}${_exec_ext}"
 else
     # Simple zip
     export APPDIR_USR=""
-    export APPDIR_BIN="${_appdir_root}"
+    export APPDIR_BIN="${APPDIR_ROOT}"
 
     _apprun_target="${APP_MAIN}${_exec_ext}"
 fi
@@ -470,7 +470,7 @@ if [ "${_kind_arg_value}" == "${_APPIMAGE_KIND}" ]; then
         _package_cmd="${_package_cmd} ${PKG_APPIMAGE_ARGS}"
     fi
 
-    _package_cmd="${_package_cmd} \"${_appdir_root}\" \"${_package_out}\""
+    _package_cmd="${_package_cmd} \"${APPDIR_ROOT}\" \"${_package_out}\""
 
     if [ ${_runapp_arg_value} == true ]; then
         _packrun_cmd="${_package_out}"
@@ -480,7 +480,7 @@ else
 
     # Simple zip
     _package_out="${PKG_OUTPUT_DIR}/${APP_MAIN}${_version_out}${_file_out_arch}.zip"
-    _package_cmd="(cd \"${_appdir_root}\" && zip -r \"${PWD}/${_package_out}\" ./)"
+    _package_cmd="(cd \"${APPDIR_ROOT}\" && zip -r \"${PWD}/${_package_out}\" ./)"
 
     if [ ${_runapp_arg_value} == true ]; then
         _packrun_cmd="${_appdir_target}"
@@ -498,7 +498,7 @@ if [ "${_kind_arg_value}" == "${_APPIMAGE_KIND}" ]; then
     _desktop="[Desktop Entry]\n"
     _desktop="${_desktop}Type=Application\n"
     _desktop="${_desktop}Name=${DE_NAME}\n"
-    _desktop="${_desktop}Exec=\"${_apprun_target}\"\n"
+    _desktop="${_desktop}Exec=AppRun\n"
     _desktop="${_desktop}Terminal=${DE_TERMINAL_FLAG}\n"
     _desktop="${_desktop}Categories=${DE_CATEGORIES}\n"
 
@@ -591,7 +591,7 @@ fi
 
 # Clean and ensure directoy exists
 ensure_directory "${PKG_OUTPUT_DIR}"
-remove_path "${_appdir_root}"
+remove_path "${APPDIR_ROOT}"
 remove_path "${_package_out}"
 ensure_directory "${APPDIR_BIN}"
 
@@ -603,13 +603,6 @@ if [ "${_publish_cmd}" != "" ]; then
     echo
 fi
 
-# Application file must exist!
-if [ ! -f "${_appdir_target}" ]; then
-    echo "Expected application file not found: ${_appdir_target}"
-    echo
-    exit 1
-fi
-
 # Post-publish
 if [ "${POST_PUBLISH}" != "" ]; then
 
@@ -618,18 +611,31 @@ if [ "${POST_PUBLISH}" != "" ]; then
 
 fi
 
+# Application file must exist!
+if [ ! -f "${_appdir_target}" ]; then
+    echo "Expected application file not found: ${_appdir_target}"
+    echo
+    exit 1
+fi
 
 if [ "${_kind_arg_value}" == "${_APPIMAGE_KIND}" ]; then
 
+    echo
+
     # Create desktop
     if [ "${_desktop}" != "" ]; then
-        echo -e "${_desktop}" > "${_appdir_root}/${APP_ID}.desktop"
+        _temp="${APPDIR_ROOT}/${APP_ID}.desktop"
+        echo "Creating: ${_temp}"
+        echo -e "${_desktop}" > "${_temp}"
         assert_result
     fi
 
     if [ "${_appxml}" != "" ]; then
-        ensure_directory "${APPDIR_USR}/share/metainfo"
-        echo -e "${_appxml}" > "${APPDIR_USR}/share/metainfo/${APP_ID}.appdata.xml"
+        _dir="${APPDIR_USR}/share/metainfo"
+        _file="${_dir}/${APP_ID}.appdata.xml"
+        echo "Creating: ${_file}"
+        ensure_directory "${_dir}"
+        echo -e "${_appxml}" > "${_file}"
         assert_result
     fi
 
@@ -642,16 +648,26 @@ if [ "${_kind_arg_value}" == "${_APPIMAGE_KIND}" ]; then
             _icon_ext=".${_icon_ext}"
         fi
 
-        cp "${APP_ICON_SRC}" "${_appdir_root}/${APP_ID}${_icon_ext}"
+        _temp="${APPDIR_ROOT}/${APP_ID}${_icon_ext}"
+        echo "Creating: ${_temp}"
+
+        cp "${APP_ICON_SRC}" "${_temp}"
         assert_result
     fi
 
-    # Simple link
-    ln -s "${_apprun_target}" "${_appdir_root}/AppRun"
-    assert_result
+    # AppRun
+    _temp="${APPDIR_ROOT}/AppRun"
+
+    if [ ! -f "${_temp}" ]; then
+
+        echo "Creating: ${_temp}"
+        ln -s "${_apprun_target}" "${_temp}"
+        assert_result
+    fi
 fi
 
 # Build package
+echo
 exec_or_die "${_package_cmd}"
 echo
 
